version: "3"
networks:
  mynet:
    driver: ${NETWORKS_DRIVER}
services:
  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: nginx
    networks:
      - mynet
    ports:
      - 80:80
      - 443:443
  php-fpm74:
    image: php:7.4.3-fpm
    environment:
      - OPCACHE_ENABLE=${OPCACHE_ENABLE}
      - OPCACHE_ENABLE_CLI=${OPCACHE_ENABLE_CLI}
    container_name: php74
    restart: unless-stopped
    networks:
      - mynet
    volumes:
      - ./php-fpm/php7.2.ini:/usr/local/etc/php/php.ini
      - ${APP_CODE_PATH_HOST}:${NGINX_DOCUMENT_ROOT}${APP_CODE_CONTAINER_FLAG}
  mysql:
      image: mysql:8.0
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      ports:
        - ${MYSQL_LOCAL_PORT}:3306
      restart: always
      volumes:
        - ${MYSQL_LOCAL_DATA}:/var/lib/mysql
      networks:
        - mynet
  redis:
      image: redis:${REDIS_VERSION}
      command: redis-server --requirepass ${REDIS_PASSWORD}
      ports:
        - ${REDIS_PORT}:6379
      networks:
        - mynet